# Workflow GitHub Actions pour déployer sur GitHub Pages
name: Déployer le contenu statique sur Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  VITE_STATSIG_CLIENT_KEY: votre_clé_client

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install

      - name: Construction du projet
        run: npm run build

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v5

      - name: Téléversement de l'artefact pour GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Assurez-vous que ce chemin correspond au dossier généré

      - name: Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
